DOCUMENT_EXTRACTION_CONFIG = {
    "document_extraction_config": {
        "version": "1.0",
        "global_rules": {
            "extract_only_if_explicitly_present": True,
            "no_inference": True,
            "no_normalization": True,
            "return_null_if_not_found": True,
        },
        "fields": [
            {
                "field_name": "PERNO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "FIRST_NAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact first name as written. On a Bahamas Passport, the 'GIVEN NAMES / PRÉNOMS' field contains both first name and middle name separated by a space (e.g. 'BRYAN IRVIN'). Extract only the FIRST word as the first name.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "MIDDLE_NAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact middle name as written. On a Bahamas Passport, the 'GIVEN NAMES / PRÉNOMS' field contains both first name and middle name separated by a space (e.g. 'BRYAN IRVIN'). Extract all words AFTER the first word as the middle name. If GIVEN NAMES contains only one word, middle name is null.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SURNAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact surname",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "DOB",
                "primary_source": "Passport",
                "fallback_sources": ["Voter Card", "Driver's License"],
                "notes": "Extract date exactly as printed",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "NI_NUMBER",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "National Insurance Number. On a Passport, extract from the MRZ (Machine Readable Zone) at the bottom of the page. The MRZ has 2 lines. In the 2nd line, the NIB number is the numeric sequence appearing on the right side after the date fields. Extract only those digits exactly as printed.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "CONTACT_MODE",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "BIRTH_NATION_NO",
                "primary_source": "Passport - Place of Birth",
                "fallback_sources": ["Voter Card"],
                "notes": "Extract place of birth exactly as written. On a Bahamas Passport, the place of birth is in the field labelled 'PLACE OF BIRTH / LIEU DE NAISSANCE' (e.g. 'LONG ISLAND', 'NEW PROVIDENCE'). Extract the value from that specific field — do not use NATIONALITY or any other field.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SMOKER",
                "primary_source": "Eapp - Question 8",
                "fallback_sources": [],
                "notes": "Extract smoker/tobacco status ONLY if the Eapp contains an explicit question about smoking or tobacco use, labelled as Question 8 or otherwise. The BAF Burial Insurance Application Form and Health Questionnaire do NOT contain a smoking question — their questions are about medical conditions (AIDS, cancer, hospital stays, medication, etc.). Do NOT extract SMOKER from any of those medical questions. If no explicit smoking question is visible in the document, return null.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "POL_REF_NO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "POLICY_NO",
                "primary_source": "Eapp - top of form reference number",
                "fallback_sources": ["Confirmation Letter - Policy #"],
                "notes": "Extract the BAF case/policy reference number. It is handwritten at the top of the Eapp form (both Application Form and Health Questionnaire), e.g. '903-256/158' or '903-256/109'. Extract it exactly as written, replacing '/' with '-' (e.g. '903-256-158'). Do NOT extract 'Policy #' numbers from confirmation letters or New Business Summary Reports unless no reference number exists on the Eapp form.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "TERM",
                "primary_source": "Available in document",
                "fallback_sources": [],
                "notes": "Extract term if explicitly present",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "START_DATE",
                "primary_source": "Eapp - Requested Date",
                "fallback_sources": [],
                "notes": "Policy requested start date",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "END_DATE",
                "primary_source": "Available in document",
                "fallback_sources": [],
                "notes": "Extract only if explicitly stated",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "FREQ",
                "primary_source": "Mode of Payment",
                "fallback_sources": [],
                "notes": "Payment frequency",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "POL_STAT",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Leave empty",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "CURRENT_BRANCH",
                "primary_source": "Eapp - Office below Agent No.",
                "fallback_sources": [],
                "notes": "Extract branch name exactly",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "PAY_ID",
                "primary_source": "Methods of Payment",
                "fallback_sources": [],
                "notes": "Extract payment method",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDRNO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR1",
                "primary_source": "Utility Bill - House No, Street Name",
                "fallback_sources": ["Eapp - House# and Street"],
                "notes": "Extract full street address line. On the Eapp APPLICATION FORM, the street address is in 'Street Address:'. On the Eapp HEALTH QUESTIONNAIRE, it is in 'Current Address:'. Use the Eapp as fallback when no Utility Bill is present.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR2",
                "primary_source": "Utility Bill - Area",
                "fallback_sources": ["Eapp - City"],
                "notes": "Extract area/locality. On the Eapp HEALTH QUESTIONNAIRE, the city/area is in the 'City:' field.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR3",
                "primary_source": "Utility Bill - Island",
                "fallback_sources": ["Eapp - Island"],
                "notes": "Extract island name. On the Eapp HEALTH QUESTIONNAIRE, the island is in the 'Island:' field.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR4",
                "primary_source": "Utility Bill - Country",
                "fallback_sources": ["Eapp - Country"],
                "notes": "Extract country exactly. On the Eapp, scan for ANY label containing the word 'Country' — including 'Country:', 'Country of Birth:', 'Country of Origin:', 'Country of Residence:'. Even if the label says 'Country of Birth', extract its value for ADDR4. Do not skip this field because of the label wording.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "POSTCODE",
                "primary_source": "Utility Bill - PO Box No",
                "fallback_sources": ["Eapp - P.O.Box"],
                "notes": "Extract PO Box or postal code. On the Eapp HEALTH QUESTIONNAIRE, the postal address/PO Box is in the 'Postal Address:' field.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "HOME_PHONES",
                "primary_source": "Eapp - Home Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written. On the Eapp APPLICATION FORM it is labelled 'Home#:'. On the Eapp HEALTH QUESTIONNAIRE it is labelled 'Home Phone:'.",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "MOBILE_PHONES",
                "primary_source": "Eapp - Mobile Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written. On the Eapp APPLICATION FORM it is labelled 'Cell#:'. On the Eapp HEALTH QUESTIONNAIRE it is labelled 'Mobile Phone:'.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "WORK_PHONES",
                "primary_source": "Eapp - Work Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "EMAILS",
                "primary_source": "Eapp - Email Address",
                "fallback_sources": [],
                "notes": "Extract exact email address. On the Eapp HEALTH QUESTIONNAIRE it is labelled 'Email:'.",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "FAX",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SMS",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
        ],
    }
}


SECTION_ORDER = [
    ("Identity", ["PERNO", "FIRST_NAME", "MIDDLE_NAME", "SURNAME", "DOB", "NI_NUMBER", "BIRTH_NATION_NO"]),
    ("Policy", ["SMOKER", "POL_REF_NO", "POLICY_NO", "TERM", "START_DATE", "END_DATE", "FREQ", "POL_STAT", "CURRENT_BRANCH", "PAY_ID"]),
    ("Address", ["ADDRNO", "ADDR1", "ADDR2", "ADDR3", "ADDR4", "POSTCODE"]),
    ("Contact", ["CONTACT_MODE", "HOME_PHONES", "MOBILE_PHONES", "WORK_PHONES", "EMAILS", "FAX", "SMS"]),
]
