DOCUMENT_EXTRACTION_CONFIG = {
    "document_extraction_config": {
        "version": "1.0",
        "global_rules": {
            "extract_only_if_explicitly_present": True,
            "no_inference": True,
            "no_normalization": True,
            "return_null_if_not_found": True,
        },
        "fields": [
            {
                "field_name": "PERNO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "FIRST_NAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact first name as written",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "MIDDLE_NAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact middle name as written",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SURNAME",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "Extract exact surname",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "DOB",
                "primary_source": "Passport",
                "fallback_sources": ["Voter Card", "Driver's License"],
                "notes": "Extract date exactly as printed",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "NI_NUMBER",
                "primary_source": "Passport",
                "fallback_sources": ["NIB Card", "Voter Card", "Driver's License"],
                "notes": "National Insurance Number",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "CONTACT_MODE",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "BIRTH_NATION_NO",
                "primary_source": "Passport - Place of Birth",
                "fallback_sources": ["Voter Card"],
                "notes": "Extract place of birth only",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SMOKER",
                "primary_source": "Eapp - Question 8",
                "fallback_sources": [],
                "notes": "Extract smoker status exactly as answered",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "POL_REF_NO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "POLICY_NO",
                "primary_source": "Available in document",
                "fallback_sources": [],
                "notes": "Extract policy number exactly",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "TERM",
                "primary_source": "Available in document",
                "fallback_sources": [],
                "notes": "Extract term if explicitly present",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "START_DATE",
                "primary_source": "Eapp - Requested Date",
                "fallback_sources": [],
                "notes": "Policy requested start date",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "END_DATE",
                "primary_source": "Available in document",
                "fallback_sources": [],
                "notes": "Extract only if explicitly stated",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "FREQ",
                "primary_source": "Mode of Payment",
                "fallback_sources": [],
                "notes": "Payment frequency",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "POL_STAT",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Leave empty",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "CURRENT_BRANCH",
                "primary_source": "Eapp - Office below Agent No.",
                "fallback_sources": [],
                "notes": "Extract branch name exactly",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "PAY_ID",
                "primary_source": "Methods of Payment",
                "fallback_sources": [],
                "notes": "Extract payment method",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDRNO",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR1",
                "primary_source": "Utility Bill - House No, Street Name",
                "fallback_sources": ["Eapp - House# and Street"],
                "notes": "Extract full street address line",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR2",
                "primary_source": "Utility Bill - Area",
                "fallback_sources": [],
                "notes": "Extract area/locality",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR3",
                "primary_source": "Utility Bill - Island",
                "fallback_sources": ["Eapp - Island"],
                "notes": "Extract island name",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "ADDR4",
                "primary_source": "Utility Bill - Country",
                "fallback_sources": [],
                "notes": "Extract country exactly",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "POSTCODE",
                "primary_source": "Utility Bill - PO Box No",
                "fallback_sources": ["Eapp - P.O.Box"],
                "notes": "Extract PO Box number",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "HOME_PHONES",
                "primary_source": "Eapp - Home Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "MOBILE_PHONES",
                "primary_source": "Eapp - Mobile Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "WORK_PHONES",
                "primary_source": "Eapp - Work Phone No.",
                "fallback_sources": [],
                "notes": "Extract exactly as written",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "EMAILS",
                "primary_source": "Eapp - Email Address",
                "fallback_sources": [],
                "notes": "Extract exact email address",
                "extraction_required": True,
                "do_not_infer": True,
            },
            {
                "field_name": "FAX",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
            {
                "field_name": "SMS",
                "primary_source": None,
                "fallback_sources": [],
                "notes": "Not available in document",
                "extraction_required": False,
                "do_not_infer": True,
            },
        ],
    }
}


SECTION_ORDER = [
    ("Identity", ["PERNO", "FIRST_NAME", "MIDDLE_NAME", "SURNAME", "DOB", "NI_NUMBER", "BIRTH_NATION_NO"]),
    ("Policy", ["SMOKER", "POL_REF_NO", "POLICY_NO", "TERM", "START_DATE", "END_DATE", "FREQ", "POL_STAT", "CURRENT_BRANCH", "PAY_ID"]),
    ("Address", ["ADDRNO", "ADDR1", "ADDR2", "ADDR3", "ADDR4", "POSTCODE"]),
    ("Contact", ["CONTACT_MODE", "HOME_PHONES", "MOBILE_PHONES", "WORK_PHONES", "EMAILS", "FAX", "SMS"]),
]
