#!/usr/bin/env python3
"""
Generate Claude extraction Excel (DQ_Anomaly_V2_Claude.xlsx).

Data extracted by Claude's own vision/OCR from all 11 PDFs.
Run this BEFORE process_pdfs.py (which deletes input PDFs).
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from app.config import OUTPUT_DIR
from app.services.excel_service import append_rows_to_excel

OUTPUT_NAME = "DQ_Anomaly_V2_Claude.xlsx"

# All 11 rows extracted by Claude vision from the PDFs.
# Field ordering matches _BASE_FIELD_COLUMNS in excel_service.py.
ROWS = [
    # ── Row 1: Bryan Mccartney (903-256-158) ───────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "BRYAN",
            "MIDDLE_NAME": "IRVIN",
            "SURNAME": "MCCARTNEY",
            "DOB": "09 NOV 1959",
            "NI_NUMBER": "14064596",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-158",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "#140 MT ROYAL AVENUE",
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "322-5320",
            "MOBILE_PHONES": "807-4221",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 2: Carmen Jones-Smith (903-256-151) ─────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "CARMEN",
            "MIDDLE_NAME": None,
            "SURNAME": "JONES-SMITH",
            "DOB": "17 MAR 1957",
            "NI_NUMBER": "30575575",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-151",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "8 ST VINCENT COVE",
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "361-5900",
            "MOBILE_PHONES": "432-5043",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 3: Catherine Forbes (903-256-164) ───────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "CATHERINE",
            "MIDDLE_NAME": "JANET",
            "SURNAME": "FORBES",
            "DOB": "15 MAY 1958",
            "NI_NUMBER": "12266582",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "LONG ISLAND",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-164",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": None,
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "601-6061",
            "MOBILE_PHONES": "425-8185",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 4: Charles L Smith (903-256-150) ────────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "CHARLES",
            "MIDDLE_NAME": "LIVINGSTONE",
            "SURNAME": "SMITH",
            "DOB": "07 DEC 1955",
            "NI_NUMBER": "14173557",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-150",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "MILE END WINTON MEADOWS",
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "698-4432",
            "MOBILE_PHONES": "447-9698",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 5: Claudette Arnette (903-256-139) ──────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "CLAUDETTE",
            "MIDDLE_NAME": "ELOISE",
            "SURNAME": "ARNETTE",
            "DOB": "04 NOV 1958",
            "NI_NUMBER": "10538585",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-139",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": None,
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": None,
            "MOBILE_PHONES": "454-5348",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 6: David Hepburn (903-256-163) ──────────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "DAVID",
            "MIDDLE_NAME": "WELLINGTON",
            "SURNAME": "HEPBURN",
            "DOB": "23 NOV 1953",
            "NI_NUMBER": "11384530",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-163",
            "TERM": "99",
            "START_DATE": "10-OCT-2025",
            "END_DATE": None,
            "FREQ": "1",
            "POL_STAT": None,
            "CURRENT_BRANCH": "Cash N Go",
            "PAY_ID": "Cash",
            "ADDRNO": None,
            "ADDR1": "#113 GILBERT ST KENNEDY SB",
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "323-7065",
            "MOBILE_PHONES": "455-7941",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "TERM": "Eapp",
            "START_DATE": "Eapp",
            "FREQ": "Eapp",
            "CURRENT_BRANCH": "Eapp",
            "PAY_ID": "Eapp",
            "ADDR1": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 7: Louise Lightbourne (903-256-83) ──────────────────────────────
    # No passport — names from NIB Card, DOB/birth place from Voter Card
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "LOUISE",
            "MIDDLE_NAME": "ICELYN",
            "SURNAME": "LIGHTBOURN",
            "DOB": "12 August 1954",
            "NI_NUMBER": "10327541",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-83",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": None,
            "ADDR2": None,
            "ADDR3": None,
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": None,
            "MOBILE_PHONES": None,
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "NIB Card",
            "MIDDLE_NAME": "NIB Card",
            "SURNAME": "NIB Card",
            "DOB": "Voter Card",
            "NI_NUMBER": "NIB Card",
            "BIRTH_NATION_NO": "Voter Card",
            "POLICY_NO": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 8: Adolphus Smith (903-256-121) ─────────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "ADOLPHUS",
            "MIDDLE_NAME": "REGINALD",
            "SURNAME": "SMITH",
            "DOB": "01 NOV 1955",
            "NI_NUMBER": "17544556",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "EXUMA",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-121",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "SERENAY COCONUT DRIVE",
            "ADDR2": "NASSAU",
            "ADDR3": "BAHAMAS",
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "341-3231",
            "MOBILE_PHONES": "454-6551",
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "ADDR2": "Eapp",
            "ADDR3": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 9: Brenda Albury (903-256-109) ──────────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "BRENDA",
            "MIDDLE_NAME": "MARIA",
            "SURNAME": "ALBURY",
            "DOB": "17 OCT 1959",
            "NI_NUMBER": "13178598",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-109",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "JOANS DRIVE HSE. #7",
            "ADDR2": "NASSAU",
            "ADDR3": "NP",
            "ADDR4": None,
            "POSTCODE": "UOGI-2124",
            "HOME_PHONES": "601-2554",
            "MOBILE_PHONES": "8070928 / 447-4000",
            "WORK_PHONES": None,
            "EMAILS": "balbury80@gmail.com",
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "ADDR2": "Eapp",
            "ADDR3": "Eapp",
            "POSTCODE": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
            "EMAILS": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 10: Bruce Johnson (903-256-114) ─────────────────────────────────
    # Passport + NIB Card both present; Passport is primary for names
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "BRUCE",
            "MIDDLE_NAME": "EDWARD",
            "SURNAME": "JOHNSON",
            "DOB": "20 JUL 1956",
            "NI_NUMBER": "10623566",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-114",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "ELIZABETH ESTATE",
            "ADDR2": "NASSAU",
            "ADDR3": "NEW PROV.",
            "ADDR4": None,
            "POSTCODE": None,
            "HOME_PHONES": "364-6262",
            "MOBILE_PHONES": None,
            "WORK_PHONES": None,
            "EMAILS": None,
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "ADDR2": "Eapp",
            "ADDR3": "Eapp",
            "HOME_PHONES": "Eapp",
        },
        "time_taken": None,
    },
    # ── Row 11: Carmen Cox (903-256-105) ────────────────────────────────────
    {
        "extracted_fields": {
            "PERNO": None,
            "FIRST_NAME": "CARMEN",
            "MIDDLE_NAME": "MURIEL",
            "SURNAME": "COX",
            "DOB": "20 FEB 1963",
            "NI_NUMBER": "10005633",
            "CONTACT_MODE": None,
            "BIRTH_NATION_NO": "NEW PROVIDENCE",
            "SMOKER": None,
            "POL_REF_NO": None,
            "POLICY_NO": "903-256-105",
            "TERM": None,
            "START_DATE": None,
            "END_DATE": None,
            "FREQ": None,
            "POL_STAT": None,
            "CURRENT_BRANCH": None,
            "PAY_ID": None,
            "ADDRNO": None,
            "ADDR1": "BLAIR AIR ESTATES",
            "ADDR2": "NASSAU",
            "ADDR3": "BAHAMAS",
            "ADDR4": None,
            "POSTCODE": "N8824",
            "HOME_PHONES": "601-4636",
            "MOBILE_PHONES": "434-6725",
            "WORK_PHONES": None,
            "EMAILS": "cxcrmn@yahoo.com",
            "FAX": None,
            "SMS": None,
        },
        "field_source": {
            "FIRST_NAME": "Passport",
            "MIDDLE_NAME": "Passport",
            "SURNAME": "Passport",
            "DOB": "Passport",
            "NI_NUMBER": "Passport",
            "BIRTH_NATION_NO": "Passport",
            "POLICY_NO": "Eapp",
            "ADDR1": "Eapp",
            "ADDR2": "Eapp",
            "ADDR3": "Eapp",
            "POSTCODE": "Eapp",
            "HOME_PHONES": "Eapp",
            "MOBILE_PHONES": "Eapp",
            "EMAILS": "Eapp",
        },
        "time_taken": None,
    },
]

if __name__ == "__main__":
    output_dir = OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / OUTPUT_NAME
    if output_path.exists():
        output_path.unlink()
    append_rows_to_excel(output_path, ROWS)
    print(f"Created: {output_path}")
    print(f"Rows written: {len(ROWS)}")
